name: Release new version
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ${{ matrix.arch.os }}
    strategy:
      matrix:
        arch:
          - os: macos-latest
            arch: darwin-amd64
          - os: ubuntu-latest
            arch: linux-amd64
        cmd:
          - cloudfront-invalidate
          - ecs-find-template-taskdef
          - ssm-delete
          - ssm-load
          - ssm-read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"
      - name: Get tag
        id: tag
        uses: jimmysawczuk/actions/github/get-tag-from-ref@main
        with:
          ref: ${{ github.ref }}
      - name: Build
        run: |
          echo "-X main.version=${{ steps.tag.outputs.tag }} -X main.revision=$GITHUB_SHA -X main.date=$(date --iso-8601=seconds)" > /tmp/buildtags
          cat /tmp/buildtags

          CGO_ENABLED=0 go build -a -o "${{ matrix.cmd }}-${{ steps.tag.outputs.tag }}-${{ matrix.arch.arch }}" -ldflags "-s -w $(cat /tmp/buildtags)" -mod=vendor ./cmd/${{ matrix.cmd }}
      - name: Upload build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.cmd }}-${{ steps.tag.outputs.tag }}-${{ matrix.arch.arch}}
          asset_name: ${{ matrix.cmd }}-${{ steps.tag.outputs.tag }}-${{ matrix.arch.arch}}
          asset_content_type: application/octet-stream
